remote_theme: mmistakes/jekyll-theme-basically-basic
title: Critical CS Education
url: https://criticalcsed.org
author: Amy J. Ko
lang: en-US
description: An NSF-funded project investigating how to prepare justice-focused middle and high school CS teachers.