theme: jekyll-theme-minimal
title: Critical CS Education
description: A website for the NSF-funded _Justice-Focused Secondary CS Education_ project, which is investigating how to prepare justice-focused middle and high school CS teachers.
show_downloads: false
logo: images/logo.png
